syntax = "proto3";

import "rust/extensions.proto";

message Update
{
  /* 源文本的语言 */
  uint32 lang = 1;
  bytes hash = 2;
  /* 语言 - 有更新的译文 */
  map<uint32, string> map = 3;
}

message Tran
{
  uint32 from_lang = 1;
  repeated uint32 to_lang_li = 2;
  string txt = 3;
  string path = 4;
}

message Job
{
  repeated Update update_li = 1 [ (rust.nullable_field) = false ];
  repeated Tran tran_li = 2 [ (rust.nullable_field) = false ];
}

message Traned 
{
  uint32 from_lang = 1;
  uint32 to_lang = 2;
  string txt = 3;
  bytes src_hash = 4;
  string path = 5;
}

message TranErr {
  uint32 from_lang = 1;
  uint32 to_lang = 2;
  string err = 3;
  string path = 4;
}

message TranResult {
  oneof kind {
    Traned traned = 1 ;
    TranErr err = 2;
  };
}

